version: '3.9'

services:
  uopp-core-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uopp-core-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: uopp-core-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: uopp_core_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/sql-init/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql

  rabbitmq:
    container_name: uopp-core-rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  postgres_data:
