spring:
  application:
    name: uopp-core
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/uopp_core_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  rabbitmq:
    processed-queue: processed_message_queue
    consumer:
      simple:
        retry:
          max-attempts: 1

    exchange: notifications
    routing-key:
      email: email-key
      telegram: telegram-key
  jobs:
    subscriptionJob:
      enabled: true
      intervalInSeconds: 30

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret: 'test-secret'
