spring:
  application:
    name: uopp-core
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/uopp_core_database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  url: http://localhost:8080
  cors:
    allowed-origins:
      - http://localhost:8081
      - http://localhost:8082
  rabbitmq:
    processed-queue: processed_message_queue
    consumer:
      simple:
        retry:
          max-attempts: 1

    exchange: notifications
    routing-key:
      email: email-key
      telegram: telegram-key
  jobs:
    subscriptionJob:
      enabled: true
      intervalInSeconds: 30

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret: 'test-secret'
